### ISSUE TITLE
Images do non appear in templates and emails in latest WP & Civi

### ISSUE THREAD

**Issue by masetto** [veda-consulting/uk.co.vedaconsulting.mosaico#393]
Hi,
in Mosaico templates the images the images do not appear. 
I don't understand why they are uploaded through this link:

```
GET https://mydomain.com/mosaico/img/?method=placeholder&params=534,200

[HTTP/1.1 401 not found]
```

I think normally it should be `https://mydomain.com/civicrm/mosaico/img/?method=placeholder&params=534,200`, **but both these url give me "401 not found"** and CIVICRM_CLEANURL is enabled.

This is my configuration:  

CiviCRM Version: 5.28.0 on Wordpress  
Mosaico 2.4.1592820024  
Wordpress: 5.5

I tried to apply [deepak-srivastava@c535f43](https://github.com/deepak-srivastava/uk.co.vedaconsulting.mosaico/commit/c535f438f05ee450c8798bd692c6add77965c8c0) but it had no effect. 

Thank you for your answers.

**Comment by mattwire** [comment]
Please see #389 and #390

**Comment by eileenmcnaughton** [comment]
@mattwire @seamuslee001 @kcristiano should we release Mosaico 2.5 for this fix

**Comment by tadcol** [comment]
@eileenmcnaughton I think so.  I left most sites on 2.3.x and have been only using 2.4 on a few.  I think a new release would be helpful.

**Comment by mattwire** [comment]
Fixed in 2.5

**Comment by masetto** [comment]
I have upgraded to Mosaico 2.5 and CiviCRM 5.28.1 (on Wordpress 5.5), but my problem remains. 
Below the screenshot:
![image](https://user-images.githubusercontent.com/9961202/90896433-eba7ec00-e3c3-11ea-9b78-98848bb091ca.png)

Note that `/mosaico/img/` after domain name does not exist. Maybe it depends on my configuration? But I can't figure out which one.
Any ideas?
Thank you
