### ISSUE TITLE
Placeholder Images Broken After Upgrade to 3.0

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#596]
Upgraded to 3.0 and plagued with image issues - on latest wordpress civi 5.61.3 - no image placeholder will show up.

Cleared cache, reloaded permalinks, 

![Screenshot 2023-06-13 at 10 57 18 AM](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/assets/28904266/5e795ac2-1306-4a93-bca9-2066325920cb)

I get this error in console. 
`Unable to preventDefault inside passive event listener invocation.
`
I have disabled and enabled it again, but no luck.

This is the path found for an image using devtools.

https://example.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fmosaico%2Fimg%2Fplaceholder&method=placeholder&params=534%2C150&text=w534

I get the following error: "Internal GD font () not available. Use only 1-5."

**Comment by bannyachanda** [comment]
Hi,

We are getting a similar error: "Internal GD font () not available. Use only 1-5.". Uploaded images are not showing in the template.
We are using CiviCRM version 5.60.0 within Wordpress version 6.2.2 and have installed Mosaico Extension version 3.0.1686233438.

**Comment by mattwire** [comment]
Fixed in 3.1

**Comment by bannyachanda** [comment]
Hi @mattwire , 
After updating the version to 3.1, the error "Internal GD font () not available. Use only 1-5." is not showing anymore. But the image placeholder issue is still there. Uploaded images are not showing in the template. See Screenshot.

<img width="2039" alt="Screenshot 2023-06-22 at 10 52 10 AM" src="https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/assets/107078418/0f9bceb6-8648-414d-a47d-b0a9a45df9aa">

**Comment by mattwire** [comment]
@bannyachanda the placeholder images are the "drop an image here 300 x 200" images which look like are working in your screenshot.
For the other images..  what happens if you upload a new image? Also try experimenting with the URL that gives the 404 in the browser console - open it in another window and see if you can see the problem with the path - the filename should exist in the same place on the filesystem.

**Comment by bannyachanda** [comment]
@mattwire 
Sorry, the screenshot I am showing is for uploaded images. I have uploaded the image, image upload is working perfectly but it is not displaying in the template. Also, the uploaded images are there in the upload directory. I can access the image src from the browser directly.
The problem happens when it's trying to display the image in the template with the URL "http://civicrm.memberlounge.ca/wp-admin/mosaico/img/?src=..."

**Comment by themak1985** [comment]
@bannyachanda - I upgraded and do not have the same issues as you do. 3.1 fixed the issue for me.

I suggest doing the following wordpress/civicrm troubleshooting.

clear civicrm cache, reload wordpress permalinks, clear civicrm cache again to be safe, create a new template.

**Comment by bannyachanda** [comment]
Hi, @themak1985, Thanks for your suggestions.  
I already did all of the things you mentioned. But still, it's not working. Even there is no error in the log files.

**Comment by bannyachanda** [comment]
Hi @mattwire,

I have figured out the problem. The image is loading from this in my Mosaico template https://mysite.com/mosaico/img/?src=.... but it should be loaded from https://mysite.com/civicrm/mosaico/img/?src=.... 

Can you please suggest to me how can I solve the problem?

**Comment by themak1985** [comment]
@bannyachanda are your resource URLs properly set?

**Comment by bannyachanda** [comment]
@themak1985 Yes I think so. Here it is: 
<img width="2043" alt="Screenshot 2023-06-23 at 12 28 39 PM" src="https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/assets/107078418/c9636e5d-66b9-4b12-b167-761ab1af5f1c">

**Comment by deepak-srivastava** [comment]
@bannyachanda For some reason your urls gone wrong.

You could try replaceurl api to correct them. E.g:

`cv api MosaicoTemplate.replaceurls from_url="https://mysite.com/mosaico/img" to_url="https://mysite.com/civicrm/mosaico/img"`

Or

`drush cvapi MosaicoTemplate.replaceurls from_url="https://mysite.com/mosaico/img" to_url="https://mysite.com/civicrm/mosaico/img"`

**Comment by bannyachanda** [comment]
Hi @deepak-srivastava, I did it. But it didn't resolve the problem. After doing it, I have got this output: 
{
    "is_error": 0,
    "version": 3,
    "count": 0,
    "values": []
}
